#define user_hostname "user_here"
#define mqtt_host "mqtt_host_here"
#define mqtt_username "mqtt_username_here"
#define mqtt_password "mqtt_password_here"
#define user_wifi_ssid "user_wifi_ssid_here"
#define user_wifi_passsword "user_wifi_passsword_here"