#include "./Pins_ESP32_S3_WROOM.h"

#define PIN_PWM_HEATER HAL_PIN_PWM_HEATER

#define PIN_VIN_ADC HAL_PIN_VIN_ADC

#define PIN_LED_DATALINE HAL_PIN_LED_DATALINE
#define LED_VOLTAGE HAL_LED_VOLTAGE
#define LED_MAX_CURRRENT HAL_LED_MAX_CURRRENT
#define LED_NUMBER HAL_LED_NUMBER
#define LED_TYPE HAL_LED_TYPE
#define LED_COLOR_ORDER HAL_LED_COLOR_ORDER

#define PIN_BUZZER_CTL HAL_PIN_BUZZER_CTL

#define PIN_I2C_SCL_LCD HAL_PIN_I2C_SCL_LCD
#define PIN_I2C_SDA_LCD HAL_PIN_I2C_SDA_LCD

#define PIN_SPI_CS_ADC HAL_PIN_SPI_CS_ADC
#define PIN_SPI_MOSI_ADC HAL_PIN_SPI_MOSI_ADC
#define PIN_SPI_SCK_ADC HAL_PIN_SPI_SCK_ADC

#define PIN_SPI_MISO_SD HAL_PIN_SPI_MISO_SD
#define PIN_SPI_MOSI_SD HAL_PIN_SPI_MOSI_SD
#define PIN_SPI_SCK_SD HAL_PIN_SPI_SCK_SD
#define PIN_SPI_CS_SD HAL_PIN_SPI_CS_SD
#define PIN_DETECT_SD HAL_PIN_DETECT_SD

#define PIN_GPIO_BUTTON_UP HAL_PIN_GPIO_BUTTON_UP
#define PIN_GPIO_BUTTON_DOWN HAL_PIN_GPIO_BUTTON_DOWN
#define PIN_GPIO_BUTTON_LEFT HAL_PIN_GPIO_BUTTON_LEFT
#define PIN_GPIO_BUTTON_RIGHT HAL_PIN_GPIO_BUTTON_RIGHT

#define PIN_SERIAL_RX_AUX HAL_PIN_SERIAL_RX_AUX
#define PIN_SERIAL_TX_AUX HAL_PIN_SERIAL_TX_AUX