#include <FastLED.h>

#define HAL_PIN_PWM_HEATER 8

#define HAL_PIN_VIN_ADC 3

#define HAL_PIN_LED_DATALINE 6
#define HAL_LED_NUMBER 1
#define HAL_LED_VOLTAGE 5
#define HAL_LED_MAX_CURRRENT 20
#define HAL_LED_TYPE WS2811
#define HAL_LED_COLOR_ORDER GRB

#define HAL_PIN_BUZZER_CTL 18

#define HAL_PIN_I2C_SCL_LCD 5
#define HAL_PIN_I2C_SDA_LCD 4

#define HAL_PIN_SPI_CS_ADC 17
#define HAL_PIN_SPI_MOSI_ADC 18
#define HAL_PIN_SPI_SCK_ADC 7

#define HAL_PIN_SPI_MISO_SD 14
#define HAL_PIN_SPI_MOSI_SD 12
#define HAL_PIN_SPI_SCK_SD 13
#define HAL_PIN_SPI_CS_SD 10
#define HAL_PIN_DETECT_SD 11

#define HAL_PIN_GPIO_BUTTON_UP 42
#define HAL_PIN_GPIO_BUTTON_DOWN 39
#define HAL_PIN_GPIO_BUTTON_LEFT 41
#define HAL_PIN_GPIO_BUTTON_RIGHT 40

#define HAL_PIN_SERIAL_RX_AUX 45
#define HAL_PIN_SERIAL_TX_AUX 48